"""Machine learning utilities for predicting audience-level movie success.

This module extends the EDA work into a supervised classification task.
It intentionally avoids recommendation-system and LLM-related features.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Iterable

import joblib
import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.dummy import DummyClassifier
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    accuracy_score,
    average_precision_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import StratifiedKFold, cross_validate, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler


TARGET_COLUMN = "success_movie"
REFERENCE_YEAR = 2017

NUMERIC_FEATURES = [
    "budget",
    "runtime",
    "popularity",
    "release_year",
    "has_budget",
    "is_english",
    "movie_age",
]
STRICT_NUMERIC_FEATURES = [
    "budget",
    "runtime",
    "release_year",
    "has_budget",
    "is_english",
    "movie_age",
]
CATEGORICAL_FEATURES = ["original_language", "main_genre"]

MODEL_FEATURES = NUMERIC_FEATURES + CATEGORICAL_FEATURES
STRICT_MODEL_FEATURES = STRICT_NUMERIC_FEATURES + CATEGORICAL_FEATURES
FEATURE_SETS = {
    "With popularity": MODEL_FEATURES,
    "Without popularity": STRICT_MODEL_FEATURES,
}
METRIC_COLUMNS = ["accuracy", "precision", "recall", "f1", "roc_auc", "pr_auc"]


def load_cleaned_movies(path: str | Path) -> pd.DataFrame:
    """Load the cleaned movie dataset generated by the data analysis notebook."""

    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Missing cleaned movie file: {path}")
    return pd.read_csv(path, low_memory=False)


def cap_series_outliers(series: pd.Series, lower_q: float = 0.01, upper_q: float = 0.99) -> pd.Series:
    """Winsorize a numeric series using quantile caps."""

    numeric = pd.to_numeric(series, errors="coerce")
    valid = numeric.dropna()
    if valid.empty:
        return numeric
    lower = valid.quantile(lower_q)
    upper = valid.quantile(upper_q)
    return numeric.clip(lower=lower, upper=upper)


def resolve_features(features: Iterable[str] | None = None) -> list[str]:
    """Return a concrete feature list."""

    return list(features) if features is not None else MODEL_FEATURES.copy()


def feature_groups(features: Iterable[str] | None = None) -> tuple[list[str], list[str]]:
    """Split a feature list into numeric and categorical columns."""

    selected = resolve_features(features)
    numeric = [feature for feature in selected if feature in NUMERIC_FEATURES]
    categorical = [feature for feature in selected if feature in CATEGORICAL_FEATURES]
    return numeric, categorical


def create_success_dataset(
    df: pd.DataFrame,
    *,
    rating_threshold: float = 7.0,
    vote_count_threshold: int = 50,
) -> tuple[pd.DataFrame, dict[str, Any]]:
    """Create features and the audience-success classification label.

    ``success_movie`` is defined as:
    ``vote_average >= 7.0 and vote_count >= 50`` by default.

    ``vote_average`` and ``vote_count`` are not used as model features because
    they define the target label and would create leakage.
    """

    model_df = df.copy()
    initial_rows = len(model_df)

    missing_target_columns = [column for column in ["vote_average", "vote_count"] if column not in model_df.columns]
    if missing_target_columns:
        raise ValueError(f"Cannot create success label. Missing columns: {missing_target_columns}")

    for column in ["budget", "runtime", "popularity", "release_year", "vote_average", "vote_count"]:
        if column not in model_df.columns:
            model_df[column] = pd.NA
        model_df[column] = pd.to_numeric(model_df[column], errors="coerce")

    for column in CATEGORICAL_FEATURES:
        if column not in model_df.columns:
            model_df[column] = "Unknown"

    model_df = model_df.dropna(subset=["vote_average", "vote_count"]).copy()

    model_df = model_df[
        (model_df["release_year"].isna())
        | ((model_df["release_year"] >= 1900) & (model_df["release_year"] <= 2020))
    ].copy()

    model_df["has_budget"] = (model_df["budget"] > 0).fillna(False).astype(int)
    model_df["is_english"] = (model_df["original_language"].astype(str).str.lower() == "en").astype(int)

    # Treat non-positive budget/runtime as unknown values, not real zeros.
    model_df.loc[model_df["budget"] <= 0, "budget"] = pd.NA
    model_df.loc[model_df["runtime"] <= 0, "runtime"] = pd.NA
    model_df.loc[model_df["runtime"] > 300, "runtime"] = pd.NA
    model_df.loc[model_df["popularity"] < 0, "popularity"] = pd.NA

    model_df["movie_age"] = REFERENCE_YEAR - model_df["release_year"]
    model_df.loc[model_df["movie_age"] < 0, "movie_age"] = 0

    for column in ["budget", "runtime", "popularity"]:
        model_df[column] = cap_series_outliers(model_df[column])

    for column in CATEGORICAL_FEATURES:
        model_df[column] = model_df[column].fillna("Unknown").astype(str)
        model_df.loc[model_df[column].str.strip() == "", column] = "Unknown"

    model_df[TARGET_COLUMN] = (
        (model_df["vote_average"] >= rating_threshold)
        & (model_df["vote_count"] >= vote_count_threshold)
    ).astype(int)

    missing_after_cleaning = {
        column: int(model_df[column].isna().sum())
        for column in ["budget", "runtime", "popularity", "release_year", "movie_age"]
        if column in model_df.columns
    }

    summary = {
        "initial_rows": int(initial_rows),
        "model_rows": int(len(model_df)),
        "positive_rows": int(model_df[TARGET_COLUMN].sum()),
        "negative_rows": int((model_df[TARGET_COLUMN] == 0).sum()),
        "positive_rate": float(model_df[TARGET_COLUMN].mean()),
        "rating_threshold": rating_threshold,
        "vote_count_threshold": vote_count_threshold,
        "reference_year_for_movie_age": REFERENCE_YEAR,
        "features": MODEL_FEATURES,
        "strict_features_without_popularity": STRICT_MODEL_FEATURES,
        "missing_after_model_cleaning": missing_after_cleaning,
    }
    return model_df, summary


def split_features(
    model_df: pd.DataFrame,
    *,
    features: Iterable[str] | None = None,
    test_size: float = 0.2,
    random_state: int = 42,
):
    """Split model features and target into train/test sets."""

    selected_features = resolve_features(features)
    missing_features = [column for column in selected_features if column not in model_df.columns]
    if missing_features:
        raise ValueError(f"Missing model feature columns: {missing_features}")

    X = model_df[selected_features].copy()
    y = model_df[TARGET_COLUMN].copy()
    return train_test_split(X, y, test_size=test_size, random_state=random_state, stratify=y)


def build_preprocessor(features: Iterable[str] | None = None) -> ColumnTransformer:
    """Create a preprocessing pipeline for numeric and categorical features."""

    numeric_features, categorical_features = feature_groups(features)
    numeric_pipeline = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="median", add_indicator=True)),
            ("scaler", StandardScaler()),
        ]
    )
    categorical_pipeline = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", min_frequency=20)),
        ]
    )
    return ColumnTransformer(
        transformers=[
            ("numeric", numeric_pipeline, numeric_features),
            ("categorical", categorical_pipeline, categorical_features),
        ]
    )


def build_models(
    *,
    features: Iterable[str] | None = None,
    random_state: int = 42,
) -> dict[str, Pipeline]:
    """Create classification models for the success-prediction module."""

    selected_features = resolve_features(features)

    def model_pipeline(classifier: Any) -> Pipeline:
        return Pipeline(
            steps=[
                ("preprocessor", build_preprocessor(selected_features)),
                ("classifier", classifier),
            ]
        )

    return {
        "Dummy Baseline": model_pipeline(DummyClassifier(strategy="most_frequent")),
        "Logistic Regression": model_pipeline(
            LogisticRegression(max_iter=2000, class_weight="balanced", random_state=random_state)
        ),
        "Random Forest": model_pipeline(
            RandomForestClassifier(
                n_estimators=300,
                random_state=random_state,
                class_weight="balanced",
                n_jobs=-1,
                min_samples_leaf=3,
            )
        ),
        "Extra Trees": model_pipeline(
            ExtraTreesClassifier(
                n_estimators=300,
                random_state=random_state,
                class_weight="balanced",
                n_jobs=-1,
                min_samples_leaf=3,
            )
        ),
    }


def get_positive_probabilities(model: Pipeline, X: pd.DataFrame) -> np.ndarray | None:
    """Return predicted probability for the positive class when available."""

    if not hasattr(model, "predict_proba"):
        return None

    probabilities = model.predict_proba(X)
    if probabilities.ndim != 2:
        return None

    classes = list(getattr(model, "classes_", []))
    if 1 in classes:
        positive_index = classes.index(1)
    elif probabilities.shape[1] >= 2:
        positive_index = 1
    else:
        return np.zeros(len(X))

    return probabilities[:, positive_index]


def evaluate_model(
    model: Pipeline,
    X_test: pd.DataFrame,
    y_test: pd.Series,
    *,
    threshold: float = 0.5,
) -> dict[str, Any]:
    """Evaluate one fitted model using threshold and probability-based metrics."""

    probabilities = get_positive_probabilities(model, X_test)
    if probabilities is None:
        predictions = model.predict(X_test)
    else:
        predictions = (probabilities >= threshold).astype(int)

    metrics: dict[str, Any] = {
        "accuracy": accuracy_score(y_test, predictions),
        "precision": precision_score(y_test, predictions, zero_division=0),
        "recall": recall_score(y_test, predictions, zero_division=0),
        "f1": f1_score(y_test, predictions, zero_division=0),
        "confusion_matrix": confusion_matrix(y_test, predictions),
    }

    if probabilities is not None:
        try:
            metrics["roc_auc"] = roc_auc_score(y_test, probabilities)
        except ValueError:
            metrics["roc_auc"] = np.nan
        try:
            metrics["pr_auc"] = average_precision_score(y_test, probabilities)
        except ValueError:
            metrics["pr_auc"] = np.nan
    else:
        metrics["roc_auc"] = np.nan
        metrics["pr_auc"] = np.nan

    return metrics


def train_and_evaluate_models(
    X_train: pd.DataFrame,
    X_test: pd.DataFrame,
    y_train: pd.Series,
    y_test: pd.Series,
    *,
    features: Iterable[str] | None = None,
    random_state: int = 42,
    model_names: Iterable[str] | None = None,
) -> tuple[dict[str, Pipeline], pd.DataFrame, dict[str, Any]]:
    """Fit selected models and return fitted models, metrics table, and raw details."""

    selected_features = resolve_features(features if features is not None else X_train.columns)
    models = build_models(features=selected_features, random_state=random_state)
    if model_names is not None:
        keep = set(model_names)
        models = {name: model for name, model in models.items() if name in keep}

    rows = []
    details: dict[str, Any] = {}

    for model_name, model in models.items():
        model.fit(X_train[selected_features], y_train)
        metrics = evaluate_model(model, X_test[selected_features], y_test)
        rows.append({"model": model_name, **{metric: metrics[metric] for metric in METRIC_COLUMNS}})
        details[model_name] = metrics

    metrics_df = pd.DataFrame(rows).sort_values(["f1", "pr_auc"], ascending=False).reset_index(drop=True)
    return models, metrics_df, details


def get_feature_names(model: Pipeline) -> list[str]:
    """Return feature names after preprocessing, including missing indicators."""

    preprocessor = model.named_steps["preprocessor"]
    numeric_features = list(preprocessor.transformers_[0][2])
    categorical_features = list(preprocessor.transformers_[1][2])

    numeric_pipeline = preprocessor.named_transformers_["numeric"]
    try:
        numeric_names = numeric_pipeline.get_feature_names_out(numeric_features).tolist()
    except AttributeError:
        numeric_names = numeric_features.copy()
        imputer = numeric_pipeline.named_steps["imputer"]
        indicator = getattr(imputer, "indicator_", None)
        if indicator is not None:
            numeric_names.extend([f"missingindicator_{numeric_features[index]}" for index in indicator.features_])

    categorical_pipeline = preprocessor.named_transformers_["categorical"]
    try:
        categorical_names = categorical_pipeline.get_feature_names_out(categorical_features).tolist()
    except AttributeError:
        encoder = categorical_pipeline.named_steps["onehot"]
        categorical_names = encoder.get_feature_names_out(categorical_features).tolist()

    return numeric_names + categorical_names


def random_forest_feature_importance(model: Pipeline, top_n: int = 15) -> pd.DataFrame:
    """Extract top tree-model feature importances."""

    classifier = model.named_steps["classifier"]
    feature_names = get_feature_names(model)
    importance = pd.DataFrame(
        {"feature": feature_names, "importance": classifier.feature_importances_}
    ).sort_values("importance", ascending=False)
    return importance.head(top_n).reset_index(drop=True)


def threshold_tuning_table(
    model: Pipeline,
    X_test: pd.DataFrame,
    y_test: pd.Series,
    *,
    thresholds: Iterable[float] = (0.3, 0.4, 0.5, 0.6, 0.7),
) -> pd.DataFrame:
    """Evaluate precision, recall, and F1 under different probability thresholds."""

    probabilities = get_positive_probabilities(model, X_test)
    if probabilities is None:
        raise ValueError("Threshold tuning requires a model with predict_proba.")

    rows = []
    for threshold in thresholds:
        predictions = (probabilities >= threshold).astype(int)
        rows.append(
            {
                "threshold": threshold,
                "precision": precision_score(y_test, predictions, zero_division=0),
                "recall": recall_score(y_test, predictions, zero_division=0),
                "f1": f1_score(y_test, predictions, zero_division=0),
                "positive_predictions": int(predictions.sum()),
            }
        )
    return pd.DataFrame(rows)


def cross_validate_model(
    model: Pipeline,
    X: pd.DataFrame,
    y: pd.Series,
    *,
    cv_splits: int = 5,
    random_state: int = 42,
) -> pd.DataFrame:
    """Run stratified cross-validation and return metric mean/std rows."""

    cv = StratifiedKFold(n_splits=cv_splits, shuffle=True, random_state=random_state)
    scoring = {
        "precision": "precision",
        "recall": "recall",
        "f1": "f1",
        "roc_auc": "roc_auc",
        "pr_auc": "average_precision",
    }
    scores = cross_validate(
        model,
        X,
        y,
        cv=cv,
        scoring=scoring,
        n_jobs=1,
        return_train_score=False,
        error_score=np.nan,
    )

    rows = []
    for metric in scoring:
        values = scores[f"test_{metric}"]
        rows.append(
            {
                "metric": metric,
                "mean": float(np.nanmean(values)),
                "std": float(np.nanstd(values)),
                "folds": cv_splits,
            }
        )
    return pd.DataFrame(rows)


def save_dataframe(df: pd.DataFrame, output_path: str | Path) -> Path:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_path, index=False)
    return output_path


def save_metrics(metrics_df: pd.DataFrame, output_path: str | Path) -> Path:
    return save_dataframe(metrics_df, output_path)


def save_models(models: dict[str, Pipeline], output_dir: str | Path) -> dict[str, Path]:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    paths: dict[str, Path] = {}
    for name, model in models.items():
        filename = name.lower().replace(" ", "_") + ".joblib"
        path = output_dir / filename
        joblib.dump(model, path)
        paths[name] = path
    return paths


def plot_model_comparison(metrics_df: pd.DataFrame, output_path: str | Path) -> Path:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    value_vars = [metric for metric in ["accuracy", "precision", "recall", "f1", "pr_auc"] if metric in metrics_df.columns]
    plot_df = metrics_df.melt(id_vars="model", value_vars=value_vars)
    sns.set_theme(style="whitegrid")
    plt.figure(figsize=(10.5, 5.6))
    sns.barplot(data=plot_df, x="model", y="value", hue="variable")
    plt.ylim(0, 1)
    plt.title("Model Performance Comparison")
    plt.xlabel("Model")
    plt.ylabel("Score")
    plt.legend(title="Metric", loc="upper right")
    plt.xticks(rotation=12, ha="right")
    plt.tight_layout()
    plt.savefig(output_path, dpi=160, bbox_inches="tight")
    plt.close()
    return output_path


def plot_confusion_matrix(
    matrix: Any,
    model_name: str,
    output_path: str | Path,
) -> Path:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    display = ConfusionMatrixDisplay(
        confusion_matrix=matrix,
        display_labels=["Not success", "Success"],
    )
    fig, ax = plt.subplots(figsize=(5.5, 4.8))
    display.plot(ax=ax, cmap="Blues", colorbar=False, values_format="d")
    ax.set_title(f"Confusion Matrix: {model_name}")
    plt.tight_layout()
    plt.savefig(output_path, dpi=160, bbox_inches="tight")
    plt.close(fig)
    return output_path


def plot_feature_importance(importance_df: pd.DataFrame, output_path: str | Path) -> Path:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    sns.set_theme(style="whitegrid")
    plt.figure(figsize=(9.5, 6))
    sns.barplot(data=importance_df, x="importance", y="feature", hue="feature", legend=False)
    plt.title("Random Forest Feature Importance")
    plt.xlabel("Importance")
    plt.ylabel("Feature")
    plt.tight_layout()
    plt.savefig(output_path, dpi=160, bbox_inches="tight")
    plt.close()
    return output_path


def plot_threshold_tuning(threshold_df: pd.DataFrame, output_path: str | Path) -> Path:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    plot_df = threshold_df.melt(
        id_vars="threshold",
        value_vars=["precision", "recall", "f1"],
        var_name="metric",
        value_name="score",
    )
    sns.set_theme(style="whitegrid")
    plt.figure(figsize=(8, 5))
    sns.lineplot(data=plot_df, x="threshold", y="score", hue="metric", marker="o")
    plt.ylim(0, 1)
    plt.title("Random Forest Threshold Tuning")
    plt.xlabel("Classification threshold")
    plt.ylabel("Score")
    plt.tight_layout()
    plt.savefig(output_path, dpi=160, bbox_inches="tight")
    plt.close()
    return output_path


def plot_cv_metrics(cv_df: pd.DataFrame, output_path: str | Path) -> Path:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    sns.set_theme(style="whitegrid")
    plt.figure(figsize=(8, 5))
    sns.barplot(data=cv_df, x="metric", y="mean", hue="metric", legend=False)
    plt.ylim(0, 1)
    plt.title("Stratified 5-Fold Cross-Validation Metrics")
    plt.xlabel("Metric")
    plt.ylabel("Mean score")
    for index, row in cv_df.reset_index(drop=True).iterrows():
        plt.errorbar(index, row["mean"], yerr=row["std"], fmt="none", c="black", capsize=4)
    plt.tight_layout()
    plt.savefig(output_path, dpi=160, bbox_inches="tight")
    plt.close()
    return output_path


def plot_popularity_comparison(comparison_df: pd.DataFrame, output_path: str | Path) -> Path:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    value_vars = [metric for metric in ["precision", "recall", "f1", "pr_auc"] if metric in comparison_df.columns]
    plot_df = comparison_df.melt(id_vars="feature_set", value_vars=value_vars)
    sns.set_theme(style="whitegrid")
    plt.figure(figsize=(8.5, 5))
    sns.barplot(data=plot_df, x="feature_set", y="value", hue="variable")
    plt.ylim(0, 1)
    plt.title("Random Forest With vs Without Popularity")
    plt.xlabel("Feature set")
    plt.ylabel("Score")
    plt.legend(title="Metric", loc="upper right")
    plt.tight_layout()
    plt.savefig(output_path, dpi=160, bbox_inches="tight")
    plt.close()
    return output_path
